development:
  store: your-store-name.myshopify.com
  password: 
  theme_id: 

staging:
  store: your-store-name.myshopify.com
  password: 
  theme_id: 

production:
  store: your-store-name.myshopify.com
  password: 
  theme_id: 