development:
  store: your_store_name.myshopify.com
  password: your_private_app_password
  theme_id: 

staging:
  store: your_store_name.myshopify.com
  password: your_private_app_password
  theme_id: 

production:
  store: your_store_name.myshopify.com
  password: your_private_app_password
  theme_id: 